version: "3"
services:
  springpart:
    build: .
    ports:
      - '8077:8077'
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    networks:
      - backend
      - frontend
    depends_on:
      - db
    restart: on-failure
  db:
    image: mysql:8.0.17
    volumes:
    -  /src/main/resources/guitarshop/currentGuitarshopData:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Abraham1203
      - MYSQL_DATABASE=guitarshop
    networks:
      - backend
  angularpart:
    build: ./guitarshop-angular-master@77ebc8ce99f
    ports:
    - '4200:80'
    networks:
      - frontend
networks:
  frontend:
  backend:




